### ISSUE TITLE
Aggregation Query (Deliverable 7)

### ISSUE THREAD

**Issue by mostlyfabulous** [mostlyfabulous/CPSC304Project#8]

**Comment by patkarns** [comment]
This part from the formal spec doesn't sound reasonable: Delivery driver can get orders and Group by delivery location and delivery time

**Comment by mostlyfabulous** [comment]
> This part from the formal spec doesn't sound reasonable: Delivery driver can get orders and Group by delivery location and delivery time

That might be tricky to pull off I agree
